### ISSUE TITLE
爬取的电影数据莫名其妙多了几个

### ISSUE THREAD

**Issue by Destiny12138** [mythsman/mouban#1]
用hexo douban命令爬完数据之后发现电影的数量比我豆瓣影单要多，仔细对比发现多了何以为家，无名之辈，红海行动三部电影，多执行了几次命令还是多这三部，请问是什么原因

**Comment by mythsman** [comment]
你的豆瓣 id 是多少，我查下。

另外这个 issue 提到 [mythsman/hexo-douban](https://github.com/mythsman/hexo-douban/issues) 下吧。

**Comment by mythsman** [comment]
看了下日志，应当是  2023-01-21 16:40 这个时间首次录入的时候是有这三部已看的，后来在  2023-01-23 23:23 这个时候更新的时候没有这三部了。

目前为了省事，我这里爬取的记录是只增不减的，所以会出现这个情况。。。

**Comment by Destiny12138** [comment]
所以目前是没有方法删除吗，除了手动删掉

**Comment by Destiny12138** [comment]
我豆瓣id是266614451，后台可以删掉这三部电影吗

**Comment by mythsman** [comment]
现在不太好删，过段时间我加下强制刷新的逻辑吧，等等🤫

**Comment by mythsman** [comment]
@Destiny12138 目前已经更新为了全量刷新，老的被取消标记的记录已经支持自动删除了。
