### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by UkokuGemini** [mythsman/mouban#3]
你好，小白一枚.

很感谢大佬做豆瓣的Api接口和缓存的服务.
我在github.io上部署了自己的网页博客(jekyll).很遗憾不是hexo,不然可以用上hexo-douban会更为方便.

幸得mouban.mythsman.com的缓存json可以拿来引用.

**但是我遇到了跨域问题，即github.io无法对mouban.mythsman.com的json做出引用.**

想来咨询一下解决的方案,能否在后端做出更为便捷的跨域的调整？

谢过.

*题外话:是否考虑给出便携的自部署方案?我想自己部署相关服务,也可以减轻服务压力.(前段时间mouban.mythsman.com好像没响应)*

再谢.

**Comment by mythsman** [comment]
1. 跨域这块的问题是我故意设置的，目前不太希望别人在页面中直接调用接口进行数据更新和查询，因为这样可能会导致访问量不可控，系统风险会比较大。所以目前还是只允许通过接口离线调用，而不允许嵌入浏览器中实时调用。
2. 其实 mouban 现在是可以通过 docker 直接部署的，但是不太建议自己部署，因为访问速率、账号、IP之类的管起来比较麻烦，处理的不好很容易中风控，比较糟心。我这里是两个账号慢慢抓了两三个月才把数据捞的差不多。
3. 服务器我是部署在 azure 云，前一段时间 azure 故障比较多，所以可用性降了不少，总体应该还好。

**Comment by mythsman** [comment]
如果实在想直接调接口，在保证不乱调用的情况下，可以把域名告诉我，我这里可以配置白名单。

**Comment by UkokuGemini** [comment]
谢过您的信任.我对Go还不太熟悉,不过也在学习.目前想法也是多看多学大佬的东西，最终转化为自己能造轮子🛞的技术.有想法自己做一个爬取功能，对于自己想实现的功能,实现只是第一步，后面还想再大展其他功能.所以这也是我想自己部署的原因.

也非常理解对于豆瓣风控机制的规避是持久存在的必要.所以觉得自部署自用还是这类工具的最终的归宿.

谢谢大佬的回复.

**Comment by UkokuGemini** [comment]
谢过您的信任.我对Go还不太熟悉,不过也在学习.目前想法也是多看多学大佬的东西，最终转化为自己能造轮子🛞的技术.有想法自己做一个爬取功能，对于自己想实现的功能,实现只是第一步，后面还想再发展其他功能.所以这也是我想自己部署的原因.

也非常理解对于豆瓣风控机制的规避是持久存在的必要.所以觉得自部署自用还是这类工具的最终的归宿.

谢谢大佬的回复.
