### ISSUE TITLE
豆瓣已经删除的条目还是拉取

### ISSUE THREAD

**Issue by maskoldboy** [mythsman/mouban#9]
豆瓣后台已经删除了些许条目，但是hexo douban还是拉取这些条目，一开始以为缓存问题，现在三天了，发现并不是

**Comment by mythsman** [comment]
https://github.com/mythsman/mouban?tab=readme-ov-file#%E5%BC%BA%E5%88%B6%E6%9B%B4%E6%96%B0%E7%94%A8%E6%88%B7

参考这里，已经删除的条目需要手动强制更新。
